{
	"up": "CREATE TABLE IF NOT EXISTS _main_log1(_id UUID NOT NULL PRIMARY KEY DEFAULT UUID_GENERATE_V4(), _message VARCHAR(255), _created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);",
	"down": "DROP TABLE IF EXISTS _main_log1;"
}